version: '3'
services:
  frontend:
    image: frontend
    build:
      context: frontend
      args:
        - API_BASE_URL:"${API_BASE_URL}"
    volumes:
      # anonymous volumes
      - /var/www/html/app/dist/
      - /var/www/html/app/node_modules/
    ports:
      - 9097:80
    restart: always
    depends_on:
      - backend

  backend:
    image: backend
    build: backend
    volumes:
      - ./backend:/usr/src/app
      # anonymous volumes
      - /usr/src/app/dist/
      - /usr/src/app/node_modules/
    restart: always
    depends_on:
      - mariadb
    env_file: .env
    entrypoint: sh -c "npm run start:$${START_MODE:-prod}"

  mariadb:
    image: mariadb:10.5.17-focal
    env_file: .env
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
