name: test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: |
        cp .env.sample .env
        docker compose up -d
        cd backend
        npm install
        npm test
      shell: bash
