name: docker ci
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: cd backend
    - run: npm install
    - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~

          test -d simple-contact-mgmt || {
            git clone git@github.com:elhardoum/simple-contact-mgmt.git simple-contact-mgmt
            cp simple-contact-mgmt/.env{.sample,}
          }

          cd simple-contact-mgmt

          # fetch updates
          git pull origin main

          # build and reboot containers
          docker compose build --no-cache
          docker compose up -d --force-recreate --renew-anon-volumes
